[package]
name = "trezor-api"
version = "0.0.0"
authors = ["Steven Roose <steven@stevenroose.org>"]

[dependencies]
log = "0.4.5"
bitcoin = "0.14"
hid = "0.3"
secp256k1 = "0.6"
protobuf = "2.0"
byteorder = "1.2"
hex = "0.3.2"

[dev-dependencies]
fern = "0.5.6"
chrono = "0.4.6"

[patch.crates-io]
bitcoin = { path = "/home/steven/code/rust/bitcoin" }

